---
title: "Code"
author: "Eric Chen, Junhan Li, & Daniel Fredin"
output: pdf_document
---

```{r include=FALSE, echo=TRUE}
# Libraries
library(tidyverse)
library(ggplot2)
library(dplyr)
library(splitstackshape)
library(readr)

library(car)
library(lmtest)
library(rcompanion)
library(olsrr)

library(maps)
library(usmap)
```

```{r include=FALSE, echo=TRUE}
# Load datasets
attorneys <- read.csv("attorneys.csv")
attorneys_time <- read.csv("attorneytimeentries.csv")
categories <- read.csv("categories.csv")
clients <- read.csv("clients.csv")
questionposts <- read.csv("questionposts.csv")
questions <- read.csv("questions.csv")
statesites <- read.csv("statesites.csv")
subcategories <- read.csv("subcategories.csv")
```

#### Data Cleaning

```{r}
# Remove unwanted columns for all datasets
attorneys <- attorneys %>%
  select(-Id, -CreatedUtc, -City, -PostalCode)

attorneys_time <- attorneys_time %>%
  select(-Id, -EnteredOnUtc, -TimeEntryUno)

categories <- categories %>%
  select(-Id)

clients <- clients %>%
  select(-Id, -PostalCode, -CreatedUtc, -InvestmentsBalance)

questionposts <- questionposts %>%
  select(-Id, -CreatedUtc)

questions <- questions %>%
  select(-Id, -AskedOnUtc, -TakenOnUtc, -ClosedOnUtc, -LegalDeadline, -ClosedByAttorneyUno)

statesites <- statesites %>%
  select(-Id)

subcategories <- subcategories %>%
  select(-Id)
```

```{r}
# Convert characters to numeric in client dataset
clients$Age <- as.integer(clients$Age)
clients$NumberInHousehold <- as.integer(clients$NumberInHousehold)
clients$AnnualIncome <- as.numeric(clients$AnnualIncome)
clients$AllowedIncome <- as.numeric(clients$AllowedIncome)
clients$CheckingBalance <- as.numeric(clients$CheckingBalance)
clients$SavingsBalance <- as.numeric(clients$SavingsBalance)
```

```{r}
# rename columns to match other datasets
questions <- questions %>%
  rename("ClientUno" = "AskedByClientUno", "AttorneyUno" = "TakenByAttorneyUno")
```

```{r}
# Merge into two dataframes

# df1 is all datasets except attorney and attorney_time
df1 <- left_join(clients, questions, join_by("StateAbbr", "ClientUno")) %>% 
  left_join(., categories, join_by("StateAbbr", "CategoryUno", "Category")) %>%
  left_join(.,subcategories, join_by("StateAbbr", "CategoryUno", "Subcategory", "SubcategoryUno")) %>%
  left_join(., questionposts, join_by("StateAbbr", "QuestionUno")) %>%
  left_join(., statesites, join_by("StateAbbr", "StateName"))

# df2 is the two attorney datasets
df2 <- left_join(attorneys, attorneys_time, join_by("StateAbbr", "AttorneyUno")) 
```

```{r}
# Select the independent variables we want to observe
# Remove all NA

data_overall <- df1 %>%
  select(StateAbbr, Age, NumberInHousehold, MaritalStatus, AnnualIncome, SavingsBalance, CheckingBalance, AllowedIncome, Category, Subcategory, ClientUno) %>%
  distinct(ClientUno, .keep_all = TRUE) %>%
  select(-ClientUno) %>%
  na.omit(df1)
```

Datasets: 
  - Statesites
    - StateAbbr
    - AllowedAssets
    - BaseIncomeLimit
    - PerHouseholdMemberIncomeLimit
    - IncomeMultiplier 
  - Client
    - StateAbbr
    - Prettymuch the entire dataset 
  - Categories
    - Category: Family and Children 
   -nSubcategories: everything related to divorces

#### Testing models

```{r}
data_overall$Subcategory <- ifelse(str_detect(data_overall$Subcategory, "Divorce"), 1, 0)
```

```{r}
model <- glm(factor(Subcategory) ~ . -Category -StateAbbr, data = data_overall, family = 'binomial')
summary(model)
```



# Visualization 1

```{r}
top_subcats <- questions %>%
  group_by(Subcategory) %>%
  summarise(num_subcats = n()) %>%
  ungroup()

top_subcats <- top_subcats %>%
  arrange(desc(num_subcats)) %>%
  head(15)

ggplot(top_subcats, aes(x = num_subcats, y = reorder(Subcategory, num_subcats))) +
  geom_bar(stat = "Identity", fill = "#00A19B") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Top 15 Subcategories",
       x = "Number of Clients",
       y = "Category")

```

# Visualization 2


# Visualization 3

